# Autogenerated wrapper script for gametracer_jll for aarch64-apple-darwin
export libgametracer

JLLWrappers.@generate_wrapper_header("gametracer")
JLLWrappers.@declare_library_product(libgametracer, "@rpath/libgametracer.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgametracer,
        "lib/libgametracer.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
